project:
  type: website

website:
  title: "ISSS624 Geospatial Analytics Application"
  navbar:
    left: 
      - text: Hands-on Exercise
        menu:
          - text: Hands-on Exercise 1
            href: Hands-On_Exercise1.qmd
          - text: Hands-on Exercise 1.1
            href: hands_on_ex1/hands_on_ex1.1.html
          - text: Hands-on Exercise 1.2
            href: hands_on_ex1/hands_on_ex1.2.html
          - text: Hands-on Exercise 2.1
            href: hands_on_ex2/hands_on_ex2.1.html
          - text: Hands-on Exercise 2.2
            href: hands_on_ex2/hands_on_ex2.2.html
          - text: Hands-on Exercise 2.3
            href: hands_on_ex2/hands_on_ex2.3.html
          - text: Hands-on Exercise 3
            href: hands_on_ex3/hands_on_ex3.html
          - text: Hands-on Exercise 4
            href: hands_on_ex4/hands_on_ex4.html
            
      - text: In-class Exercise
        menu: 
          - text: In-class Exercise 1
            href: in_class_ex1/in_class_ex1.html
          - text: In-class Exercise 1 Updated
            href: in_class_ex1/in_class_ex1_updated.html
          - text: In-class Exercise 2.1
            href: in_class_ex2/in_class_ex2.html
          - text: In-class Exercise 2.2
            href: in_class_ex2/in_class_ex2.1.html
          - text: In-class Exercise 3
            href: in_class_ex3/in_class_ex3.html
          - text: In-class Exercise 4
            href: in_class_ex4/in_class_ex4.html
          - text: In-class Exercise 4.1
            href: in_class_ex4/in_class_ex4.1.html
          - text: In-class Exercise 5
            href: in_class_ex5/in_class_ex5.html
            
      - text: Take-Home Exercise
        menu: 
          - text: Take-Home Exercise 1
            href: take_home_ex1/take_home_ex1.html
          - text: Take-Home Exercise 2
            href: take_home_ex2/take_home_ex2.html
            
      
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

